Repository distributed-system-analysis/pbench, pull requests merged in 2019-06, with the labels that each got.

#1211 Wrap jschart with React component for handling reloading/resetting
  web-server/v0.4/package.json
  web-server/v0.4/src/components/TimeseriesGraph/index.js
  web-server/v0.4/src/pages/RunComparison/index.js
Labels: Pbench Dashboard, enhancement

#1188 e2e testing for controller, results, and search pages using Puppeteer
  web-server/v0.4/README.md
  web-server/v0.4/package.json
  web-server/v0.4/src/e2e/controllers.e2e.js
  web-server/v0.4/src/e2e/results.e2e.js
  web-server/v0.4/src/e2e/search.e2e.js
Labels: Pbench Dashboard, Unit tests

#1233 Add iteration port filtering
  web-server/v0.4/src/components/TableFilterSelection/index.js
  web-server/v0.4/src/models/dashboard.js
  web-server/v0.4/src/pages/ComparisonSelect/index.js
  web-server/v0.4/src/utils/parse.js
Labels: Pbench Dashboard, enhancement

#1230 pbench-move-results: Quote variables in conditional expressions
  agent/util-scripts/pbench-move-results
Labels: Agent, bug, in progress

#1175 Matrix visualization for increase/decrease in percentage for comparison cluster
  web-server/v0.4/src/pages/RunComparison/index.js
  web-server/v0.4/src/pages/RunComparison/index.test.js
  web-server/v0.4/src/utils/parse.js
Labels: Pbench Dashboard, enhancement

#1239 Filter iteration hostname & ports by `all` keyword on component update
  web-server/v0.4/src/components/TableFilterSelection/index.js
  web-server/v0.4/src/utils/parse.js
Labels: Pbench Dashboard, enhancement

#1236 Integrate Explore page for discovering and launching shared dashboard sessions
  web-server/v0.4/README.md
  web-server/v0.4/config/router.config.js
  web-server/v0.4/mock/datastoreConfig.js.example
  web-server/v0.4/src/common/menu.js
  web-server/v0.4/src/models/explore.js
  web-server/v0.4/src/pages/Explore/index.js
  web-server/v0.4/src/services/explore.js
Labels: Pbench Dashboard, enhancement

#1243 Reference selectedIterations via global redux store namespace
  web-server/v0.4/src/models/global.js
  web-server/v0.4/src/pages/ComparisonSelect/index.js
  web-server/v0.4/src/pages/RunComparison/index.js
Labels: Pbench Dashboard, bug

#1231 Fix uperf runtime padding
  agent/bench-scripts/pbench-uperf
Labels: Agent, bug, uperf

#1246 Resolve linting errors
  web-server/v0.4/package.json
  web-server/v0.4/src/layouts/BasicLayout.js
Labels: Pbench Dashboard, bug

#1241 Fix iteration port filtering and clearing for Summary and Comparison Select page
  web-server/v0.4/src/components/TableFilterSelection/index.js
  web-server/v0.4/src/pages/Summary/index.js
Labels: Pbench Dashboard, enhancement
